server:
  port: 9003

spring:
  application:
    name: NOTIFICATION-SERVICE

ureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hotsname: localhost